### ISSUE TITLE
Develop or Master?

### ISSUE THREAD

**Issue by sigaretim** [koseven/koseven.ga#10]
Hi there, 
I'm a little confused. 
The site offers the download version (https://github.com/koseven/koseven/archive/3.3.9.zip ,unknown branch), at the same time on the Github there are versions of the master and devel.

The master version is "3.3.8 cubelles", and the usual one that the site offers is "3.3.9 karlsruhe".
If master (default stable) version 3.3.3 is a cuballas, then what does the site offer? And why is the difference between the site and githup repo?

Which source is the stable production version?

**Comment by jstrobel** [comment]
@toitzi Merged today the master so now it is 3.3.9. Thanks for reporting.
