### ISSUE TITLE
Feedback on new site.

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven.ga#13]

**Comment by neo22s** [comment]
- maybe we should use our logo
- links not working 
![image](https://user-images.githubusercontent.com/241725/53327977-42c12380-38e9-11e9-8f99-22a57b5d5cf5.png)
- some images not loading http://toitzi-koseven.at/documentation/codebench/

**Comment by jstrobel** [comment]
You are faster than me, so no need to open the Link-Issue :)

**Comment by toitzi** [comment]
@neo22s Thanks for the review. fixing those. 
One question: Are you sure you want the "koseven Framework" text switched with our logo?
Here are two examples of how it would look:

![screen1](https://user-images.githubusercontent.com/42447585/53335123-e36c0f00-38fa-11e9-9050-00b65745aef1.PNG)
![screen2](https://user-images.githubusercontent.com/42447585/53335125-e36c0f00-38fa-11e9-89bf-466ead39712d.PNG)

**Comment by neo22s** [comment]
I think so we will need to modify the css to use the colors of the logo and thats all...no?

**Comment by toitzi** [comment]
You mean like this? If yes please choose one (My personal choice would be blue)

![second](https://user-images.githubusercontent.com/42447585/53338507-33030880-3904-11e9-9dda-6a38407d561f.PNG)
Full Blue

![third](https://user-images.githubusercontent.com/42447585/53338510-34343580-3904-11e9-8616-b53597648612.PNG)
Full Orange

![first](https://user-images.githubusercontent.com/42447585/53338512-34343580-3904-11e9-8737-12fa68ae3271.PNG)
30/70

**Comment by jstrobel** [comment]
Full blue :ok_hand:

**Comment by toitzi** [comment]
Fixed this issue!
