### ISSUE TITLE
mcrypt_get_key_size DEPRECATED in PHP 7.1.0

### ISSUE THREAD

**Issue by seraguirre** [koseven/koseven.ga#4]
This function has been DEPRECATED as of PHP 7.1.0. Relying on this function is highly discouraged.

modules/encrypt/classes/Kohana/Encrypt/Engine/Mcrypt.php

**Comment by jstrobel** [comment]
Hi @seraguirre this is the repository of the "website" so please open such issues in the main repository koseven/koseven. I think there is one: https://github.com/koseven/koseven/issues/200
I close this here.
